<?php

return [
    [
        'slug' => 'karsten-walter-artcom-music-group',
        'category' => 'Signing News',
        'date' => '06.10.2026',
        'time' => '10:00',
        'title' => 'Karsten Walter unterschreibt bei der Artcom Music Group',
        'subtitle' => 'Neue Musik und ein neues Album für 2027',
        'image' => 'images/news/karsten-walter-signing.jpeg',
        'pdf' => 'files/news/pressemitteilung-karsten-walter-artcom.pdf',
        'caption' => 'v.l. Kathleen Herrmann (Consulting Music, Head of Video Production & TV Marketing), Karsten Walter, Felix Kahlbaum (Director A&R). Foto: Felix Pinzke',
        'excerpt' => 'Die Artcom Music Group begrüßt Karsten Walter im Label. Gemeinsam entsteht neue Musik, die 2027 in Form eines neuen Albums veröffentlicht wird.',
        'body' => [
            'Die Artcom Music Group begrüßt mit Karsten Walter einen Künstler, der wie kaum ein anderer für moderne Emotionalität und Leidenschaft im Pop-Schlager steht. Gemeinsam mit dem Berliner Label arbeitet der Sänger und Schauspieler an neuer Musik, die 2027 in Form eines neuen Albums veröffentlicht wird. Seine neue Single „Mr. Right“ gibt bereits einen Einblick wohin die musikalische Reise geht.',
            'Die Authentizität und Nahbarkeit von Karsten trifft auf eine moderne Soundvision und eine große Liebe zur Musik. Diese Kombination bildet die Basis für eine Zusammenarbeit, bei der ein neues musikalisches Kapitel aufgeschlagen werden soll.',
            'Karsten Walter:',
            '„Ich freue mich sehr auf die Zusammenarbeit mit der Artcom Music Group und darauf, gemeinsam neue musikalische Wege zu gehen. Für mich ist Musik immer eine Möglichkeit, Emotionen auszudrücken, Geschichten zu erzählen und Menschen zu erreichen. Ich habe große Lust, mich musikalisch weiterzuentwickeln, neue Einflüsse aufzunehmen und dabei trotzdem meiner eigenen Linie treu zu bleiben. Mit meiner neuen Musik möchte ich genau das verbinden und ein neues Kapitel aufschlagen, auf das ich mich unglaublich freue.',
            'Felix Kahlbaum, Director A&R:',
            '„Wir haben Karsten Walter als Künstler kennengelernt, der eine klare Vorstellung davon hat, wo er musikalisch hinmöchte und gleichzeitig offen für neue Impulse ist. Genau diese Kombination macht die Zusammenarbeit für uns so spannend. Wir freuen uns darauf, gemeinsam mit Karsten an seinem neuen Album zu arbeiten und seine musikalische Entwicklung langfristig zu begleiten.“',
            '2026 ist für Karsten ein Jahr voller kreativer Energie: neue Musik, neue Impulse und ein Team, das sein Potenzial fördert und ihm Raum gibt, seine künstlerische Identität weiter zu formen.',
            'Kontakt:',
            'Felix Kahlbaum',
            'music@artcom-group.com',
            'M: +49 172 6106075',
        ],
    ],
    [
        'slug' => 'daniela-alfinito-artcom-music-group',
        'category' => 'Signing News',
        'date' => '01.10.2026',
        'time' => '10:00',
        'title' => 'Daniela Alfinito wechselt zur Artcom Music Group',
        'subtitle' => 'Neuer Sound und neue Wege',
        'image' => 'images/news/daniela-alfinito-signing.jpeg',
        'pdf' => 'files/news/pressemitteilung-daniela-alfinito-artcom.pdf',
        'caption' => 'v.l. Felix Kahlbaum, Marko Wünsch, Daniela Alfinito, Kathleen Hermann und Florian Mollitor. Foto: Lea Bauer',
        'excerpt' => 'Die Artcom Music Group begrüßt Daniela Alfinito im Label. Mit neuem Sound, bewahrter Authentizität und dem Album Seelenflüstern startet sie in ein neues Kapitel.',
        'body' => [
            'Die Artcom Music Group freut sich, eine einzigartige neue Künstlerin im Label zu begrüßen: Daniela Alfinito. Sie ist eine der erfolgreichsten Schlagersängerinnen Deutschlands. Durch ihre einmalig-authentische Art hat sie sich einen festen Platz in der Musiklandschaft erarbeitet. Ihre Erfolge sprechen eine eindeutige Sprache.',
            'Ihr außergewöhnlicher Karriereweg ist bemerkenswert. Die Tochter von Bernd Ulrich (Die Amigos) arbeitet trotz zahlreicher Erfolge weiterhin als Altenpflegerin in Hessen. Mit dem Album „Du warst jede Träne wert“, erreichte sie erstmals den Platz 1 der Album-Charts 2019 und verdrängte sogar Udo Lindenberg vom Thron. Ihre Alben begeistern hunderttausende Fans. Mehr als 5mal erreichte sie Platz 1 der offiziellen Album-Charts. Ihre erste offizielle Goldene Schallplatte für mehr als 100.000 verkaufte Einheiten bestätigen die Richtigkeit ihrer Bodenständigkeit.',
            'Daniela Alfinito wechselt nicht nur zur Artcom Music Group, sondern sie geht musikalisch neue Wege und bleibt sich dennoch treu. Sie arbeitet weiterhin mit Autoren wie Matthias Teriet, Marvin Trecha, Jascha Welzel und Alexander Scholz zusammen. Seit über einem Jahrzehnt ist sie ihren Autorenteams treu. Mit ihrem neuen Studioalbum geht sie aber musikalisch neue Wege. Ihr Sound ist komplett überarbeitet. Daniela Alfinito klingt wertiger, anspruchsvoller und zeitentsprechend als je zuvor. Sie arbeitet hier mit Hens Hensen zusammen, der sich für die Produktion verantwortlich zeigt. Die erste Single „Seelenflüstern“ aus ihrem gleichnamigen Album stellt das eindrucksvoll unter Beweis. Ihre Single erscheint am 2. Oktober 2026, die das neue Studioalbum für Januar 2027 ankündigt.',
            'Daniela Alfinito: „Ich blicke zurück und bin vor allem dankbar. Dankbar für die Menschen, die meine Musik über all die Jahre begleitet haben, und für die vielen Geschichten, die wir gemeinsam erlebt haben. Für mich ist es wichtig, meinen eigenen Weg zu gehen und dabei authentisch zu bleiben. Die Gespräche mit der Artcom Music Group haben sich von Anfang an richtig angefühlt, und deshalb freue ich mich sehr auf alles, was vor uns liegt.“',
            'Marko Wünsch: „Daniela Alfinito hat alles erreicht, was sie nicht zu träumen gewagt hat. Sie legt sich nicht auf die faule Haut. Nein, sie setzt alles auf eine Karte und wagt den Neuanfang. Absoluter Respekt! Neues Label, neuer Produzent, neuer Sound - Ein grandioser Neustart! Mein Team und ich sind stolz, mit Daniela in die neue Zukunft zu gehen. Die Zukunft beginnt jetzt! Das Schlagerjahr 2027 gehört Daniela Alfinito.“',
            'Kontakt:',
            'Florian Mollitor',
            'music@artcom-group.com',
        ],
    ],
    [
        'slug' => 'norman-langen-artcom-music-group',
        'category' => 'Signing News',
        'date' => '30.09.2026',
        'time' => '09:30',
        'title' => 'Norman Langen unterschreibt bei der Artcom Music Group',
        'subtitle' => 'Ein neues Kapitel im deutschen Schlager',
        'image' => 'images/news/norman-langen-signing.jpeg',
        'pdf' => 'files/news/pressemitteilung-norman-langen-artcom.pdf',
        'caption' => 'v.l. Felix Kahlbaum, Marko Wünsch, Norman Langen, Florian Mollitor und Kathleen Herrmann. Foto: Lea Bauer',
        'excerpt' => 'Mit der Vertragsunterzeichnung bei der Artcom Music Group schlägt Norman Langen ein neues Kapitel auf. Sein neues Studioalbum Liebe schafft das schon erscheint im Januar 2027.',
        'body' => [
            'Mit der Vertragsunterzeichnung beim aufstrebenden Label Artcom Music Group schlägt der wohl beliebteste Schlagerkünstler Deutschlands ein neues Kapitel auf. Mit seinem neuen Studioalbum „Liebe schafft das schon“ bestätigt Norman Langen seine Liebe zum Deutschen Schlager. Der Klang ist neu und frisch, dennoch bleibt Norman Langen sich und dem Deutschen Schlager treu.',
            'Das neue Studioalbum ist ab sofort im Vorverkauf erhältlich und wird im Januar 2027 veröffentlicht. Seine Authentizität und unverwechselbare Stimme geben dem Album die besondere Note. Norman Langen arbeitete hier u.a. mit Autoren wie Anja Krabbe, Alexander Scholz, Hens Hensen und Tom Marquardt. Auch das unterstreicht sein Bekenntnis zum Deutschen Schlager. Für die Produktion ist federführend Hens Hensen verantwortlich.',
            'Norman Langen: „Ich freue mich riesig über diese Zusammenarbeit. Ein neuer Abschnitt beginnt, mit einem Team, das meine Vision teilt und mich versteht. Die Artcom Music Group ist genau der richtige Partner, um meinen musikalischen Weg zu gehen. Ich brenne darauf, neue Songs zu präsentieren. Ich kann es kaum noch erwarten.“',
            'Marko Wünsch: „Seit über einem Jahrzehnt arbeiten wir bereits intensiv zusammen. Ich freue mich sehr, dass wir diesen neuen Weg gemeinsam gehen. Norman steht für mich nicht nur für Kontinuität und absolute Professionalität, sondern auch für unfassbares Talent: Norman ist und bleibt der große Sympathieträger des Deutschen Schlagers!“',
            'Kontakt:',
            'Florian Mollitor',
            'music@artcom-group.com',
        ],
    ],
];
